ansible_user: cloud_user
img_filename: admin.jpg
bg_img_url: https://thumbs.dreamstime.com/z/isolated-headshot-african-american-business-woman-ceo-finance-law-attorney-legal-representative-white-background-167982948.jpg
