---
# tasks file for dev
- name: Install docker prerequisities
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Make sure that /etc/apt/keyrings dir exists
  file:
    path: /etc/apt/keyrings
    state: directory
  become: yes

- name: Add GPG key for docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
  become: yes

- name: Add repo to source lists
  shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu eoan stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  become: yes

# - name: Install docker, git and docker-compose
#   apt:
#     name: 
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#       - docker-compose-plugin
#       - git
#       - docker-compose
#     state: present
#     update_cache: yes
#   become: yes

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
  become: yes

- name: Add users to group "docker"
  ansible.builtin.user:
    name: "{{ default_docker_group_users }}"
    groups: docker
    append: yes
  become: yes



